name: terraform

on:
  pull_request:
    branches: [main]
    paths: ['remediations/**', '.github/workflows/terraform.yml']
  push:
    branches: [main]
    paths: ['remediations/**', '.github/workflows/terraform.yml']

env:
  AWS_REGION: us-east-1
  TF_VERSION: "1.12.0"
  TF_DIR: remediations/01-s3-public

jobs:
  plan:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - uses: aws-actions/configure-aws-credentials@v6.2.3
        with:
          role-to-assume: arn:aws:iam::143037703701:role/gha-terraform-plan
          role-session-name: gha-plan-${{ github.run_id }}
          aws-region: ${{ env.AWS_REGION }}

      - run: aws sts get-caller-identity

      - name: Terraform init
        run: terraform init
        working-directory: ${{ env.TF_DIR }}

      - name: Terraform plan
        id: plan
        run: terraform plan -no-color -input=false
        working-directory: ${{ env.TF_DIR }}
        continue-on-error: true

      - name: Comment plan on PR
        uses: actions/github-script@v7
        with:
          script: |
            const body = `#### Terraform Plan — \`${{ steps.plan.outcome }}\`
            <details><summary>Show plan</summary>

            \`\`\`terraform
            ${{ steps.plan.outputs.stdout }}
            \`\`\`
            </details>`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body
            })

      - name: Fail if plan errored
        if: steps.plan.outcome == 'failure'
        run: exit 1

  apply:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    environment: production
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - uses: aws-actions/configure-aws-credentials@v6.2.3
        with:
          role-to-assume: arn:aws:iam::143037703701:role/gha-terraform-apply
          role-session-name: gha-apply-${{ github.run_id }}
          aws-region: ${{ env.AWS_REGION }}

      - run: aws sts get-caller-identity

      - name: Terraform init
        run: terraform init
        working-directory: ${{ env.TF_DIR }}

      - name: Terraform apply
        run: terraform apply -auto-approve -input=false
        working-directory: ${{ env.TF_DIR }}